##
##
## This is a sample parameters.yml file. Your installation will need at
## least these parameters. Use this file to customize your installation
## and tell Symfony about your database and Solr servers.
##
## This file must be copied into the ./dev/ and ./prod/ directories:
## ./dev/parameters.yml will have your Dev database and Solr installation
## ./prod/parameters.yml will have the production info
##
## If you use git/github, MAKE SURE ALL THESE FILES ARE IN YOUR .GITIGNORE!!!
## You should see the line "app/config/**/parameters.yml" in there by default.
##
##


parameters:
  #
  # Set these parameters for your installation so we can use them in our templates
  # Some of this information is used in the Structured Data output
  #
    site_name: "Generic Data Catalog"
    site_description: "This is a generic description of a generic data catalog."
    site_base_url: "http://www.example.com"
    site_provider_name: "Generic Library or Department that Made the Data Catalog"
    site_provider_url: "http://library.example.edu"
    institution_name: "Generic Academic Institution"
    institution_name_short: "Our Institution"
    institution_address: "123 Fake Street, Springfield USA"
    institution_url: "http://www.example.edu"
    
    # Options for the contact form
    contact_email_to: 
    contact_email_from: 
    institutional_affiliation_options:
      - "Generic School of Medicine"
      - "Generic School of Engineering"
      - "Generic School of Etc."

    # Badge to display for internal datasets
    internal_dataset_text: "Internal Dataset"

    # Tag to display for local experts (if you want to specify the institution)
    local_expert_display: "Local Expert"

  #
  # Technical stuff
  #
    database_driver: pdo_mysql
    database_name: datacatalog
    database_host: localhost
    database_user: root
    database_password: root
    database_port:
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: J3tfF3ulcAN7m3lTSte3lB3Ams
    # If you're using LDAP authentication
    ldap.host:
    ldap.port: 

  #
  # Solr stuff. You mostly want to set the server URL and 
  # choose your facets.
  # The other settings are a bit more involved to change.
  #
    solrsearchr_server: http://localhost:8983/solr/datacatalog/
    solrsearchr_format: json
    #
    # Comment out any 'solrsearchr_facets' below that
    # you don't want to appear on the results page.
    #
    solrsearchr_facets:
        - origin_fq
        - subject_domain_fq
        - subject_geographic_area_fq
        - access_restrictions_fq
    solrsearchr_fields_to_search: 
        - _text_
    solrsearchr_fields_to_display:
        - id
        - origin
        - dataset_title
        - dataset_alt_title
        - authors
        - description
        - subject_domain
        - access_restrictions
        - local_experts
        - subject_geographic_area
        - dataset_start_date
        - dataset_end_date
